"""Mod Projects: the shareable form of a converted character.

A Mod Project holds only the creator's own files (model + textures) and a recipe, mod.json. Create Mod reads it,
takes the original package from the *recipient's own* installation and rebuilds the finished game files locally with
the same converter (studio_core.convert_job -> mk11.convert.convert) the creator used.

Mod Projects are untrusted input. mod.json is pure data: nothing in it is executed, downloaded or expanded, and every
file it names must be a plain file inside the project folder (no '..', absolute paths, links or junctions).
Finished game packages (.xxx/.psf) and other game data are refused, both when a project is created and when one is
used.
"""
import datetime
import hashlib
import json
import os
import re
import shutil
import stat
import struct

import numpy as np

import studio_core as core
from mk11.oodle import MK11Error
from mk11.package import Package
from mk11 import mesh as M, texture as T, convert as CV
from mk11.gltf import GLB, to_game

FORMAT_VERSION = 1
MANIFEST = "mod.json"
README = "README.txt"
DO_NOT_REDISTRIBUTE = core.DO_NOT_REDISTRIBUTE_FILE

# limits for untrusted projects
MAX_MANIFEST = 1 << 20
MAX_FILES = 200
MAX_TOTAL = 2 << 30
MAX_GLB = 1 << 30
MAX_IMAGE = 256 << 20
MAX_TEXT = 1 << 20
MAX_IMAGE_SIDE = 8192
MAX_HIDDEN = 500

IMAGE_EXT = {".png", ".jpg", ".jpeg", ".tga", ".bmp", ".tif", ".tiff", ".webp"}
TEXT_EXT = {".txt", ".md"}
ALLOWED_EXT = IMAGE_EXT | TEXT_EXT | {".glb", ".json"}

PKG_TAG = b"\xC1\x83\x2A\x9E"                                   # MK11/UE3 package and compressed-segment tag
SEGMENT_SIG = PKG_TAG + b"\0\0\0\0" + struct.pack("<Q", 0x20000)  # start of every compressed MK11 data block
MAGIC = [(b"PK\x03\x04", "a ZIP archive"), (b"PK\x05\x06", "a ZIP archive"),
         (b"7z\xBC\xAF\x27\x1C", "a 7-Zip archive"), (b"Rar!", "a RAR archive"), (b"\x1F\x8B", "a compressed archive"),
         (b"MSCF", "a CAB archive"), (b"DDS ", "a DDS texture (the game's texture format)"),
         (b"#!", "a script"), (PKG_TAG, "a Mortal Kombat 11 package file")]

REFUSE_EXPLAIN = ("A Mod Project may contain only your own model, your own textures, mod.json and text files. "
                  "Finished or original Mortal Kombat 11 files, game data, archives and programs are not allowed.")

MISSING_GAME_FILE = ("Required Mortal Kombat 11 file not found:\n\n{files}\n\nCreate Mod requires this file from your own "
                     "Mortal Kombat 11 installation and cannot provide missing game files.")

REDISTRIBUTION_WARNING = (
    "Mod created successfully\n\n"
    "The finished Mortal Kombat 11 package files generated by Create Mod are intended for your local installation.\n\n"
    "Do not redistribute or upload the generated .xxx, .psf, or other Mortal Kombat 11 package files. These files "
    "may contain original Mortal Kombat 11 game data.\n\n"
    "If you want to share this mod with other people, share the Mod Project containing the custom assets and "
    "mod.json instead. Other users should run Create Mod with their own Mortal Kombat 11 installation to generate "
    "the required game files locally.")

PROJECT_README = """{name}
{underline}
{byline}{description}
HOW TO INSTALL

1. Install MK11 Character Studio.
2. Open Create Mod ("Create Mod.cmd" in the MK11 Character Studio folder).
3. Select this mod's mod.json file.
4. Select your Mortal Kombat 11 installation if requested.
5. Press Create Mod.
6. The required modified game files will be generated locally.

This download does not contain the original Mortal Kombat 11 package files required by the mod.
Base character: {character} (needs {files} from your own installation).

Do not redistribute the generated .xxx/.psf files.
Share this Mod Project instead.

Made with MK11 Character Studio {version}, an unofficial community tool not affiliated with Warner Bros. Games or
NetherRealm Studios. Mortal Kombat and its characters belong to their respective owners.
"""


class ModProjectError(MK11Error):
    pass


# ============================================================================================ paths
SAFE_PART = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 _.()\[\]-]{0,99}$")
SAFE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 _.()\[\]-]{0,63}$")
RESERVED = {"CON", "PRN", "AUX", "NUL"} | {"COM%d" % i for i in range(1, 10)} | {"LPT%d" % i for i in range(1, 10)}
OBJECT_PATH = re.compile(r"^[A-Za-z0-9_]{1,128}(\.[A-Za-z0-9_]{1,128}){0,15}$")
PACKAGE = re.compile(r"^GEARASSETS_([A-Z0-9]{2,4})_ScriptAssets$")
SOLID = re.compile(r"^solid:(\d{1,3}),(\d{1,3}),(\d{1,3}),(\d{1,3})$")
VERSION = re.compile(r"^(\d{1,4})\.(\d{1,4})(?:\.(\d{1,4}))?$")


_LINK_TAGS = {getattr(stat, "IO_REPARSE_TAG_SYMLINK", 0xA000000C), getattr(stat, "IO_REPARSE_TAG_MOUNT_POINT", 0xA0000003)}


def _is_link(path):
    """Symbolic link or junction. (Other reparse points, e.g. OneDrive placeholders, are ordinary files; anything that
    still resolves outside the project is caught by the realpath check in resolve_in.)"""
    try:
        st = os.lstat(path)
    except OSError:
        return False
    return stat.S_ISLNK(st.st_mode) or getattr(st, "st_reparse_tag", 0) in _LINK_TAGS


def check_rel_path(rel, what="path"):
    """A path written in mod.json: relative, '/'-separated, plain names only. Returns its parts."""
    if not isinstance(rel, str) or not rel or len(rel) > 240:
        raise ModProjectError("mod.json: %s must be a short relative path inside the Mod Project" % what)
    bad = [c for c in ("\\", ":", "%", "$", "~", "\0", "//", "?", "*", "<", ">", "|", '"') if c in rel]
    if bad or rel.startswith("/"):
        raise ModProjectError("mod.json: %s '%s' is not allowed (only relative paths inside the Mod Project)" % (what, rel))
    parts = rel.split("/")
    for p in parts:
        if p in (".", "..") or not SAFE_PART.match(p) or p.endswith((".", " ")) or p.split(".")[0].upper() in RESERVED:
            raise ModProjectError("mod.json: %s '%s' is not allowed (only relative paths inside the Mod Project)"
                                  % (what, rel))
    return parts


def resolve_in(root, rel, what="file"):
    """Absolute path of a project file, guaranteed to be a regular file inside `root` (no links/junctions)."""
    parts = check_rel_path(rel, what)
    path = root
    for p in parts:
        path = os.path.join(path, p)
        if _is_link(path):
            raise ModProjectError("%s '%s' is a link or junction; Mod Projects may only contain plain files" % (what, rel))
    real, real_root = os.path.realpath(path), os.path.realpath(root)
    if not core.inside(real, real_root) or os.path.normcase(real) == os.path.normcase(real_root):
        raise ModProjectError("%s '%s' points outside the Mod Project" % (what, rel))
    if not os.path.isfile(path):
        raise ModProjectError("%s '%s' is missing from the Mod Project" % (what, rel))
    return path


def safe_name(name, default="file"):
    """A file/folder name that passes check_rel_path (used when copying the creator's files)."""
    base, ext = os.path.splitext(os.path.basename(name))
    base = re.sub(r"[^A-Za-z0-9 _()\[\]-]+", "_", base).strip(" ._") or default
    if not base[0].isalnum():
        base = "f" + base
    if base.split(".")[0].upper() in RESERVED:
        base += "_"
    return base[:60] + re.sub(r"[^a-z0-9.]", "", ext.lower())


def sha256(path):
    return CV.sha256(path)


# ============================================================================================ file checks
def sniff(path):
    """What a file really is, from its content. Returns (kind, description) with kind in
    'glb', 'image', 'text', 'forbidden'."""
    with open(path, "rb") as f:
        head = f.read(4096)
    if head[:2] == b"MZ" and len(head) >= 64:              # Windows program/library: MZ header pointing at 'PE\0\0'
        pe = struct.unpack_from("<I", head, 0x3C)[0]
        with open(path, "rb") as f:
            f.seek(pe)
            if f.read(4) == b"PE\0\0":
                return "forbidden", "a Windows program or library"
    for sig, desc in MAGIC:
        if head.startswith(sig):
            return "forbidden", desc
    if head[:4] == b"glTF":
        return "glb", "glTF binary"
    ext = os.path.splitext(path)[1].lower()
    if ext in IMAGE_EXT:
        return "image", "image"
    if ext in TEXT_EXT or os.path.basename(path) == MANIFEST:
        try:
            with open(path, "rb") as f:
                data = f.read(MAX_TEXT + 1)
            if b"\0" in data:
                raise ValueError
            data.decode("utf-8")
        except ValueError:
            return "forbidden", "a binary file named like a text file"
        return "text", "text"
    return "forbidden", "a '%s' file" % (ext or "extension-less")


def contains_game_data(path):
    """True if the file contains a compressed MK11 data block anywhere (e.g. a package hidden inside another file)."""
    with open(path, "rb") as f:
        prev = b""
        while True:
            chunk = f.read(8 << 20)
            if not chunk:
                return False
            if SEGMENT_SIG in prev[-(len(SEGMENT_SIG) - 1):] + chunk:
                return True
            prev = chunk


def check_glb_file(path):
    """Structural checks of an untrusted .glb (self-contained, parseable)."""
    size = os.path.getsize(path)
    if size > MAX_GLB:
        raise ModProjectError("%s is larger than %d MB" % (os.path.basename(path), MAX_GLB >> 20))
    try:
        g = GLB(path)
    except Exception as e:
        raise ModProjectError("%s is not a valid .glb file (%s)" % (os.path.basename(path), e))
    for kind in ("buffers", "images"):
        for item in g.j.get(kind, []):
            if "uri" in item:
                raise ModProjectError("%s refers to an external file or URL (%s); only self-contained .glb files "
                                      "are allowed" % (os.path.basename(path), kind))
    if not g.j.get("skins"):
        raise ModProjectError("%s has no armature/skin" % os.path.basename(path))
    return g


def check_image_file(path):
    from PIL import Image
    if os.path.getsize(path) > MAX_IMAGE:
        raise ModProjectError("%s is larger than %d MB" % (os.path.basename(path), MAX_IMAGE >> 20))
    try:
        with Image.open(path) as im:
            w, h = im.size
            im.verify()
    except Exception as e:
        raise ModProjectError("%s is not a readable image (%s)" % (os.path.basename(path), e))
    if w > MAX_IMAGE_SIDE or h > MAX_IMAGE_SIDE:
        raise ModProjectError("%s is %dx%d; images up to %d px per side are supported"
                              % (os.path.basename(path), w, h, MAX_IMAGE_SIDE))


def scan_project(root):
    """Every file in a project folder must be an allowed, honest type; no links, programs, archives or game data.
    Returns the list of relative paths (for reporting)."""
    bad, files, total = [], [], 0
    for d, dirs, fs in os.walk(root, followlinks=False):
        for x in list(dirs):
            if _is_link(os.path.join(d, x)):
                bad.append("%s: a link or junction" % os.path.relpath(os.path.join(d, x), root))
                dirs.remove(x)
        for x in fs:
            p = os.path.join(d, x); rel = os.path.relpath(p, root).replace("\\", "/")
            if _is_link(p):
                bad.append("%s: a link or junction" % rel); continue
            files.append(rel); total += os.path.getsize(p)
            ext = os.path.splitext(x)[1].lower()
            if ext not in ALLOWED_EXT or (ext == ".json" and x != MANIFEST):
                bad.append("%s: '%s' files are not allowed" % (rel, ext or x)); continue
            kind, desc = sniff(p)
            if kind == "forbidden":
                bad.append("%s: is %s" % (rel, desc)); continue
            if (ext == ".glb") != (kind == "glb") or (ext in IMAGE_EXT) != (kind == "image"):
                bad.append("%s: content does not match its extension" % rel); continue
            if kind == "text" and os.path.getsize(p) > MAX_TEXT:
                bad.append("%s: text file larger than 1 MB" % rel); continue
            if contains_game_data(p):
                bad.append("%s: contains Mortal Kombat 11 package data" % rel)
    if len(files) > MAX_FILES:
        bad.append("more than %d files" % MAX_FILES)
    if total > MAX_TOTAL:
        bad.append("larger than %d GB in total" % (MAX_TOTAL >> 30))
    if bad:
        raise ModProjectError("This Mod Project contains files that are not allowed:\n- " + "\n- ".join(bad[:20])
                              + "\n\n" + REFUSE_EXPLAIN)
    return files


# ============================================================================================ original-data detection
class GameIndex:
    """Fingerprints of the original meshes and textures in the base package, used to recognise game data that a
    model or texture would otherwise carry into a Mod Project. Nothing from it is ever written anywhere."""
    GRID = 20               # vertex positions compared on a 0.05 cm grid
    MESH_SHARE = 0.25       # a mesh is 'original' when >= 25% of its vertices sit on original vertices ...
    MESH_MIN = 50           # ... and at least 50 of them do
    # images are compared as 32x32 RGB: an image is 'original' when its structure correlates >= IMAGE_CORR with an
    # original texture AND its colours are within IMAGE_MAE (0-255). Near-flat images carry no picture to compare.
    IMAGE_CORR = 0.95
    IMAGE_MAE = 24.0
    IMAGE_MIN_STD = 3.0

    def __init__(self, game_dir, package):
        self.package = package
        self.xxx, self.psf = core.pkg_path(game_dir, package)
        self._keys = self._prints = self._names = None

    @staticmethod
    def _key(pos):
        q = np.round(np.asarray(pos, np.float64) * GameIndex.GRID).astype(np.int64) + (1 << 20)
        return (q[:, 0] << 42) | (q[:, 1] << 21) | q[:, 2]

    @staticmethod
    def fingerprint(im):
        """(32x32 RGB values, their z-scores or None for near-flat images)."""
        from PIL import Image
        fp = np.asarray(im.convert("RGB").resize((32, 32), Image.BOX), np.float32)
        sd = float(fp.std())
        return fp, ((fp - fp.mean()) / sd if sd >= GameIndex.IMAGE_MIN_STD else None)

    def _load(self):
        if self._keys is not None:
            return
        p = Package(self.xxx)
        keys, prints, names = [], [], set()
        with open(self.psf, "rb") as f:
            for e in p.exports:
                cls = p.class_name(e["index"])
                if cls == "SkeletalMesh":
                    for l in M.mesh_info(p, e["index"])["lods"]:
                        if not l["streamed"]:
                            continue
                        try:
                            keys.append(self._key(M.read_lod(CV.read_lod_raw(p, l, f)[1])["pos"]))
                        except Exception:
                            pass
                elif cls == "Texture2D":
                    names.add(p.obj_name(e["index"]).lower())
                    try:
                        t = T.read_texture(p, e["index"])
                        if min(t["w"], t["h"]) < 16:
                            continue
                        cands = ([m for m in t["mips"] if min(m["w"], m["h"]) >= 64] or
                                 [m for m in t["mips"] if min(m["w"], m["h"]) >= 32] or t["mips"][-1:])
                        m = cands[-1]
                        fp, z = self.fingerprint(T.decode(t["fmt"], max(4, m["w"]), max(4, m["h"]),
                                                          T.read_mip(p, t, m, f), t["srgb"]))
                        if z is not None:
                            prints.append((p.obj_name(e["index"]), fp, z))
                    except Exception:
                        pass
        self._keys = np.unique(np.concatenate(keys)) if keys else np.zeros(0, np.int64)
        self._prints, self._names = prints, names

    def mesh_problem(self, label, positions_gltf):
        self._load()
        k = self._key(to_game(positions_gltf))
        hit = int(np.isin(k, self._keys).sum())
        if hit >= self.MESH_MIN and hit >= self.MESH_SHARE * len(k):
            return ("%s matches an original Mortal Kombat 11 mesh (%d%% of its vertices sit exactly on original "
                    "vertices). Export only the objects you made." % (label, round(100.0 * hit / len(k))))
        return None

    def image_problem(self, label, image, name=""):
        self._load()
        stem = os.path.splitext(os.path.basename(name or ""))[0].lower()
        if stem and stem in self._names:
            return "%s is named like the original game texture '%s'" % (label, stem)
        fp, z = self.fingerprint(image)
        if z is None:
            return None
        for oname, ofp, oz in self._prints:
            if float((z * oz).mean()) >= self.IMAGE_CORR and float(np.abs(fp - ofp).mean()) <= self.IMAGE_MAE:
                return "%s looks like the original game texture '%s'" % (label, oname)
        return None

    def image_scores(self, image):
        """(best correlation, its colour difference, texture name) - for calibration and diagnostics."""
        self._load()
        fp, z = self.fingerprint(image)
        if z is None:
            return None
        return max(((float((z * oz).mean()), float(np.abs(fp - ofp).mean()), n) for n, ofp, oz in self._prints),
                   default=None)


def originality_problems(glb_path, image_paths, index):
    """Problems for a model + texture files that carry original game data (empty list = OK)."""
    from PIL import Image
    import io
    probs = []
    g = GLB(glb_path)
    gen = str(g.j.get("asset", {}).get("generator", ""))
    model = os.path.basename(glb_path)
    if gen.startswith(core.APP):
        probs.append("%s was written by MK11 Character Studio from game files (an export or a preview), not by you"
                     % model)
    for m in g.j.get("meshes", []):
        for k, pr in enumerate(m.get("primitives", [])):
            if "POSITION" in pr.get("attributes", {}):
                pb = index.mesh_problem("%s: mesh '%s'%s" % (model, m.get("name", "?"), " part %d" % k if k else ""),
                                        g.accessor(pr["attributes"]["POSITION"]))
                if pb:
                    probs.append(pb)
    for i, im in enumerate(g.j.get("images", [])):
        try:
            img = Image.open(io.BytesIO(g.image_bytes(i)))
            pb = index.image_problem("%s: embedded image '%s'" % (model, im.get("name", i)), img, im.get("name", ""))
        except ModProjectError:
            raise
        except Exception:
            pb = None
        if pb:
            probs.append(pb)
    for path in image_paths:
        with Image.open(path) as img:
            pb = index.image_problem("texture %s" % os.path.basename(path), img, path)
        if pb:
            probs.append(pb)
    return probs


# ============================================================================================ manifest
def _version_tuple(v):
    m = VERSION.match(v) if isinstance(v, str) else None
    if not m:
        raise ModProjectError("mod.json: minimum_studio_version '%s' is not a version like 1.0.0" % v)
    return tuple(int(x or 0) for x in m.groups())


def _text(value, field, limit, multiline=False):
    if not isinstance(value, str) or len(value) > limit:
        raise ModProjectError("mod.json: '%s' must be text of at most %d characters" % (field, limit))
    allowed = "\n\t" if multiline else ""
    if any(ord(c) < 32 and c not in allowed for c in value):
        raise ModProjectError("mod.json: '%s' contains control characters" % field)
    return value


def _rgba(spec, field):
    if not (isinstance(spec, list) and len(spec) == 4 and all(isinstance(x, int) and not isinstance(x, bool)
                                                              and 0 <= x <= 255 for x in spec)):
        raise ModProjectError("mod.json: %s must be four numbers 0-255" % field)
    return spec


def _check_defaults(d):
    if not isinstance(d, dict) or set(d) != {"color_parameter", "parameters", "rules"}:
        raise ModProjectError("mod.json: textures.defaults must contain color_parameter, parameters and rules")
    if d["color_parameter"] not in core.TEX_PARAMS:
        raise ModProjectError("mod.json: textures.defaults.color_parameter is not a known texture")
    if not isinstance(d["parameters"], dict) or not set(d["parameters"]) <= set(core.TEX_PARAMS):
        raise ModProjectError("mod.json: textures.defaults.parameters lists unknown textures")
    for k, v in d["parameters"].items():
        m = SOLID.match(v) if isinstance(v, str) else None
        if not m or any(int(x) > 255 for x in m.groups()):
            raise ModProjectError("mod.json: textures.defaults.parameters.%s must be 'solid:R,G,B,A'" % k)
    if not isinstance(d["rules"], dict) or not set(d["rules"]) <= set(core.TEX_PARAMS):
        raise ModProjectError("mod.json: textures.defaults.rules lists unknown textures")
    for k, r in d["rules"].items():
        if not isinstance(r, dict) or not set(r) <= {"flip_green", "alpha"}:
            raise ModProjectError("mod.json: textures.defaults.rules.%s has unknown settings" % k)
        if "flip_green" in r and not isinstance(r["flip_green"], bool):
            raise ModProjectError("mod.json: textures.defaults.rules.%s.flip_green must be true/false" % k)
        if "alpha" in r and not (isinstance(r["alpha"], int) and not isinstance(r["alpha"], bool) and 0 <= r["alpha"] <= 255):
            raise ModProjectError("mod.json: textures.defaults.rules.%s.alpha must be 0-255" % k)


TOP_KEYS = {"format_version", "minimum_studio_version", "created_with", "name", "author", "description", "base",
            "model", "textures", "hidden_meshes", "output_name", "files"}
REQUIRED = TOP_KEYS - {"created_with", "author", "description"}


def validate_manifest(m):
    """Check a parsed mod.json completely. Version checks come first so a newer format is never guessed at.
    Returns the set of project files it references."""
    if not isinstance(m, dict):
        raise ModProjectError("mod.json is not a Mod Project manifest")
    fv = m.get("format_version")
    if not isinstance(fv, int) or isinstance(fv, bool) or fv < 1:
        raise ModProjectError("mod.json: format_version is missing or invalid")
    if fv != FORMAT_VERSION:
        raise ModProjectError("This mod uses Mod Project format version %d.\n\nYour version of MK11 Character Studio "
                              "supports version %d.\n\nPlease update MK11 Character Studio." % (fv, FORMAT_VERSION))
    need = _version_tuple(m.get("minimum_studio_version"))
    if need > _version_tuple(core.VERSION):
        raise ModProjectError("This mod requires MK11 Character Studio %s or newer.\n\nYou have version %s.\n\n"
                              "Please update MK11 Character Studio." % (m["minimum_studio_version"], core.VERSION))
    unknown = sorted(set(m) - TOP_KEYS)
    if unknown:
        raise ModProjectError("mod.json: unknown settings %s" % unknown)
    missing = sorted(REQUIRED - set(m))
    if missing:
        raise ModProjectError("mod.json: missing settings %s" % missing)
    _text(m["name"], "name", 80)
    if not m["name"].strip():
        raise ModProjectError("mod.json: name is empty")
    for f, lim in (("author", 80), ("created_with", 80)):
        if f in m:
            _text(m[f], f, lim)
    if "description" in m:
        _text(m["description"], "description", 2000, multiline=True)
    if not isinstance(m["output_name"], str) or not SAFE_NAME.match(m["output_name"]) or \
            m["output_name"].endswith((".", " ")) or m["output_name"].split(".")[0].upper() in RESERVED:
        raise ModProjectError("mod.json: output_name must be a simple folder name")
    b = m["base"]
    if not isinstance(b, dict) or not {"character", "package", "game_files", "target_mesh"} <= set(b) or \
            not set(b) <= {"character", "character_name", "package", "game_files", "target_mesh"}:
        raise ModProjectError("mod.json: base must contain character, package, game_files and target_mesh")
    pm = PACKAGE.match(b["package"]) if isinstance(b["package"], str) else None
    if not pm:
        raise ModProjectError("mod.json: base.package must be a character package like GEARASSETS_LIU_ScriptAssets")
    if b["character"] != pm.group(1):
        raise ModProjectError("mod.json: base.character does not match base.package")
    if b["game_files"] != [b["package"] + ".xxx", b["package"] + ".psf"]:
        raise ModProjectError("mod.json: base.game_files must be the package's .xxx and .psf")
    if "character_name" in b:
        _text(b["character_name"], "base.character_name", 60)
    if not isinstance(b["target_mesh"], str) or not OBJECT_PATH.match(b["target_mesh"]):
        raise ModProjectError("mod.json: base.target_mesh is not a valid object name")
    hm = m["hidden_meshes"]
    if not isinstance(hm, list) or len(hm) > MAX_HIDDEN or len(set(map(str, hm))) != len(hm) or \
            not all(isinstance(h, str) and OBJECT_PATH.match(h) for h in hm):
        raise ModProjectError("mod.json: hidden_meshes must be a list of unique object names")
    refs = {}
    check_rel_path(m["model"], "model")
    if not m["model"].lower().endswith(".glb"):
        raise ModProjectError("mod.json: model must be a .glb file")
    refs[m["model"]] = "model"
    tx = m["textures"]
    if not isinstance(tx, dict) or set(tx) != {"mode", "assignments", "defaults"}:
        raise ModProjectError("mod.json: textures must contain mode, assignments and defaults")
    if tx["mode"] not in ("replace", "keep_all"):
        raise ModProjectError("mod.json: textures.mode must be 'replace' or 'keep_all'")
    if not isinstance(tx["assignments"], dict) or not set(tx["assignments"]) <= set(core.TEX_PARAMS):
        raise ModProjectError("mod.json: textures.assignments lists unknown textures")
    for param, a in tx["assignments"].items():
        if not isinstance(a, dict) or a.get("source") not in ("file", "solid", "keep"):
            raise ModProjectError("mod.json: textures.assignments.%s.source must be file, solid or keep" % param)
        expect = {"file": {"source", "path"}, "solid": {"source", "rgba"}, "keep": {"source"}}[a["source"]]
        if set(a) != expect:
            raise ModProjectError("mod.json: textures.assignments.%s has unexpected settings" % param)
        if a["source"] == "file":
            check_rel_path(a["path"], "texture %s" % param)
            if os.path.splitext(a["path"])[1].lower() not in IMAGE_EXT:
                raise ModProjectError("mod.json: texture %s must be an image file (%s)" % (param, ", ".join(sorted(IMAGE_EXT))))
            refs[a["path"]] = "texture %s" % param
        elif a["source"] == "solid":
            _rgba(a["rgba"], "textures.assignments.%s.rgba" % param)
    _check_defaults(tx["defaults"])
    files = m["files"]
    if not isinstance(files, dict) or set(files) != set(refs):
        raise ModProjectError("mod.json: 'files' must list exactly the model and texture files the mod uses")
    for rel, info in files.items():
        if not isinstance(info, dict) or set(info) != {"sha256", "size"} or not re.match(r"^[0-9a-f]{64}$", str(info["sha256"])) \
                or not isinstance(info["size"], int) or isinstance(info["size"], bool) or info["size"] < 0:
            raise ModProjectError("mod.json: files.%s needs a sha256 and size" % rel)
    return refs


def _no_duplicates(pairs):
    keys = [k for k, _ in pairs]
    if len(keys) != len(set(keys)):
        raise ModProjectError("mod.json: a setting appears twice")
    return dict(pairs)


class Project:
    def __init__(self, root, manifest, refs):
        self.root, self.m, self.refs = root, manifest, refs

    @property
    def name(self):
        return self.m["name"]

    def path(self, rel):
        return resolve_in(self.root, rel, self.refs.get(rel, "file"))

    def texture_files(self):
        return [a["path"] for a in self.m["textures"]["assignments"].values() if a["source"] == "file"]


def load_project(path):
    """Open and fully validate a Mod Project (folder or its mod.json). Raises ModProjectError with a message
    meant for the user."""
    path = os.path.abspath(path)
    if os.path.isdir(path):
        path = os.path.join(path, MANIFEST)
    if os.path.basename(path).lower() != MANIFEST:
        raise ModProjectError("Select the mod's mod.json file (unzip the download first).")
    root = os.path.dirname(path)
    if _is_link(path) or _is_link(root):
        raise ModProjectError("mod.json or its folder is a link or junction; Mod Projects may only contain plain files")
    if not os.path.isfile(path):
        raise ModProjectError("mod.json not found in %s" % root)
    if os.path.getsize(path) > MAX_MANIFEST:
        raise ModProjectError("mod.json is too large to be a Mod Project manifest")
    try:
        with open(path, "rb") as f:
            m = json.loads(f.read().decode("utf-8"), object_pairs_hook=_no_duplicates)
    except ModProjectError:
        raise
    except Exception as e:
        raise ModProjectError("mod.json is not valid JSON (%s)" % e)
    refs = validate_manifest(m)
    scan_project(root)
    proj = Project(root, m, refs)
    for rel, what in refs.items():
        full = proj.path(rel)
        info = m["files"][rel]
        if os.path.getsize(full) != info["size"] or sha256(full) != info["sha256"]:
            raise ModProjectError("%s (%s) does not match mod.json: the file is damaged or was changed after the mod "
                                  "was made. Download the mod again." % (rel, what))
        if what == "model":
            check_glb_file(full)
        else:
            check_image_file(full)
    return proj


# ============================================================================================ creator side
def project_dir(workspace, name):
    return os.path.join(workspace, "mod_projects", name)


def _source_problems(path, what, workspace, game_dir):
    probs = []
    if not os.path.isfile(path):
        return ["%s '%s' was not found" % (what, path)]
    if _is_link(path):
        probs.append("%s %s is a link; select the real file" % (what, os.path.basename(path)))
    for folder, label in ((game_dir, "your Mortal Kombat 11 folder"),
                          (os.path.join(workspace, "exports"), "the exports folder (original game meshes and textures)"),
                          (os.path.join(workspace, "converted"), "the converted folder (finished game files)"),
                          (os.path.join(workspace, "created_mods"), "the created_mods folder (finished game files)"),
                          (os.path.join(workspace, "mod_projects"), "the mod_projects folder")):
        if folder and core.inside(path, folder):
            probs.append("%s %s comes from %s" % (what, os.path.basename(path), label))
    if os.path.isfile(os.path.join(os.path.dirname(path), core.EXPORT_NOTE_FILE)):
        probs.append("%s %s sits in an export folder of original game files" % (what, os.path.basename(path)))
    ext = os.path.splitext(path)[1].lower()
    kind, desc = sniff(path)
    want = "glb" if what == "model" else "image"
    if kind != want or (want == "image" and ext not in IMAGE_EXT) or (want == "glb" and ext != ".glb"):
        probs.append("%s %s is %s, not %s" % (what, os.path.basename(path), desc,
                                             "a .glb model" if want == "glb" else "an image (%s)" % ", ".join(sorted(IMAGE_EXT))))
    elif contains_game_data(path):
        probs.append("%s %s contains Mortal Kombat 11 package data" % (what, os.path.basename(path)))
    else:
        try:
            check_glb_file(path) if want == "glb" else check_image_file(path)
        except ModProjectError as e:
            probs.append(str(e))
    return probs


def create_project(workspace, game_dir, package, mesh, model, name, textures, keep_textures, hidden, defaults,
                   author="", description="", log=print):
    """Write <workspace>\\mod_projects\\<name>\\ = mod.json + README.txt + the creator's own model/texture files.
    Refuses (ModProjectError) if any file isn't the creator's own or the result would contain game data."""
    title = (name or "").strip()
    if not title or len(title) > 80 or any(ord(c) < 32 for c in title):
        raise ModProjectError("the mod needs a short name (the output name)")
    folder = re.sub(r"[^A-Za-z0-9 _.()\[\]-]+", "_", title).strip(" ._")[:64] or "mod"
    if not folder[0].isalnum() or folder.split(".")[0].upper() in RESERVED:
        folder = "mod_" + folder
    pm = PACKAGE.match(package)
    if not pm:
        raise ModProjectError("Mod Projects support character packages (GEARASSETS_*_ScriptAssets) only")
    textures = dict(textures or {})
    tex_files = {p: v for p, v in textures.items() if v not in ("keep",) and not str(v).startswith("solid:")}
    probs = _source_problems(model, "model", workspace, game_dir)
    for p, v in tex_files.items():
        probs += _source_problems(v, "texture %s" % p, workspace, game_dir)
    if not probs:
        probs = originality_problems(model, sorted(set(tex_files.values())), GameIndex(game_dir, package))
    if probs:
        raise ModProjectError("not created, because it would contain files that aren't yours to share:\n- "
                              + "\n- ".join(probs) + "\n\n" + REFUSE_EXPLAIN)
    pkg = Package(core.pkg_path(game_dir, package)[0])
    mesh = pkg.full_path(pkg.find(mesh, "SkeletalMesh"))      # unique full object path (bare names can repeat)
    final = project_dir(workspace, folder)
    stage = final + ".building"
    if os.path.exists(stage):
        shutil.rmtree(stage)
    os.makedirs(os.path.join(stage, "assets", "textures"))
    files, used = {}, set()

    def put(src, sub):
        n = safe_name(src)
        b, e = os.path.splitext(n); k = 1
        while (sub + "/" + n).lower() in used:
            k += 1; n = "%s_%d%s" % (b, k, e)
        rel = sub + "/" + n; used.add(rel.lower())
        shutil.copyfile(src, os.path.join(stage, *rel.split("/")))
        files[rel] = dict(sha256=sha256(os.path.join(stage, *rel.split("/"))), size=os.path.getsize(src))
        return rel

    model_rel = put(model, "assets")
    copied, assignments = {}, {}
    for param in core.TEX_PARAMS:
        if param not in textures:
            continue
        v = textures[param]
        if v == "keep":
            assignments[param] = {"source": "keep"}
        elif str(v).startswith("solid:"):
            assignments[param] = {"source": "solid", "rgba": list(CV.solid(v))}
        else:
            if v not in copied:
                copied[v] = put(v, "assets/textures")
            assignments[param] = {"source": "file", "path": copied[v]}
    snap = {"color_parameter": defaults.get("color_parameter", "ColorOverride"),
            "parameters": dict(defaults.get("parameters", {})),
            "rules": {k: {x: y for x, y in r.items() if not x.startswith("_")} for k, r in defaults.get("rules", {}).items()}}
    code = pm.group(1)
    manifest = {
        "format_version": FORMAT_VERSION,
        "minimum_studio_version": core.MIN_PROJECT_STUDIO_VERSION,
        "created_with": "%s %s" % (core.APP, core.VERSION),
        "name": title, "author": author or "", "description": description or "",
        "base": {"character": code, "character_name": core.character_name(package), "package": package,
                 "game_files": [package + ".xxx", package + ".psf"], "target_mesh": mesh},
        "model": model_rel,
        "textures": {"mode": "keep_all" if keep_textures else "replace", "assignments": assignments, "defaults": snap},
        "hidden_meshes": sorted(hidden),
        "output_name": folder,
        "files": files,
    }
    validate_manifest(manifest)                               # what we write must pass our own reader
    with open(os.path.join(stage, MANIFEST), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    byline = ("by %s\n" % author) if author else ""
    with open(os.path.join(stage, README), "w", encoding="utf-8") as f:
        f.write(PROJECT_README.format(name=title, underline="=" * len(title), byline=byline,
                                      description=(description.strip() + "\n") if description and description.strip() else "",
                                      character=core.character_name(package) or code,
                                      files=" and ".join(manifest["base"]["game_files"]), version=core.VERSION))
    scan_project(stage)                                       # final guarantee: nothing but allowed, honest files
    load_project(os.path.join(stage, MANIFEST))
    if os.path.exists(final):
        old = final + ".old-" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        os.rename(final, old); log("previous Mod Project kept as %s" % os.path.basename(old))
    os.rename(stage, final)
    return final


# ============================================================================================ recipient side
def required_files(project, game_dir):
    """[(file name, full path, exists)] of the original game files the mod needs from the user's installation."""
    out = []
    for fn in project.m["base"]["game_files"]:
        full = os.path.join(game_dir or "", "Asset", fn)
        out.append((fn, full, bool(game_dir) and os.path.isfile(full)))
    return out


def summary(project, game_dir=None):
    m = project.m; b = m["base"]
    lines = [m["name"], ""]
    if m.get("author"):
        lines += ["Author:", m["author"], ""]
    lines += ["Base character:", b.get("character_name") or core.character_name(b["package"]) or b["character"], ""]
    lines += ["Required local game files:"] + [fn for fn, _, _ in required_files(project, game_dir)] + [""]
    lines += ["Custom model:", os.path.basename(m["model"]), ""]
    tf = project.texture_files()
    lines += ["Custom textures:"] + ([os.path.basename(t) for t in tf] or ["(none - uses the model's own colours "
                                                                           "and neutral defaults)"]) + [""]
    lines += ["The original Mortal Kombat 11 files will be read from your own installation."]
    return "\n".join(lines)


def build_project(project, game_dir, workspace, log=print):
    """Recreate the mod's finished game files in <workspace>\\created_mods\\<output_name>\\ from the user's own
    installation, with the same converter the creator used. Returns the output folder."""
    missing = [fn for fn, _, ok in required_files(project, game_dir) if not ok]
    if missing:
        raise ModProjectError(MISSING_GAME_FILE.format(files="\n".join(missing)))
    core.check_folders(workspace, game_dir)
    m = project.m
    out = os.path.join(workspace, "created_mods", m["output_name"])
    if core.inside(out, project.root) or core.inside(project.root, out):
        raise ModProjectError("Choose an output folder outside the Mod Project folder (generated game files must "
                              "never end up inside a Mod Project).")
    for rel, info in m["files"].items():                   # unchanged since it was validated
        if sha256(project.path(rel)) != info["sha256"]:
            raise ModProjectError("%s changed after the mod was opened; open the mod again" % rel)
    log("Checking the mod's files against your installation's original game data...")
    probs = originality_problems(project.path(m["model"]), [project.path(t) for t in project.texture_files()],
                                 GameIndex(game_dir, m["base"]["package"]))
    if probs:
        raise ModProjectError("This Mod Project contains original Mortal Kombat 11 data, so Create Mod won't use it:\n- "
                              + "\n- ".join(probs) + "\n\n" + REFUSE_EXPLAIN)
    textures = {}
    for param, a in m["textures"]["assignments"].items():
        textures[param] = ("keep" if a["source"] == "keep" else "solid:%d,%d,%d,%d" % tuple(a["rgba"])
                           if a["source"] == "solid" else project.path(a["path"]))
    return core.convert_job(workspace, game_dir, m["base"]["package"], m["base"]["target_mesh"], project.path(m["model"]),
                            m["output_name"], textures=textures, keep_textures=m["textures"]["mode"] == "keep_all",
                            hide=set(m["hidden_meshes"]), log=log, defaults=m["textures"]["defaults"],
                            make_project=False, subdir="created_mods")
